"""create genres platforms and companies tables

Revision ID: 40f7055ece98
Revises: ac419f0354b7
Create Date: 2026-09-26 23:55:04.699625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f7055ece98'
down_revision: Union[str, Sequence[str], None] = 'ac419f0354b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('igdb_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('igdb_id')
    )
    op.create_table('genres',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('igdb_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('igdb_id')
    )
    op.create_table('platforms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('igdb_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('igdb_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platforms')
    op.drop_table('genres')
    op.drop_table('companies')
    # ### end Alembic commands ###
