"""create library_entries table

Revision ID: 5bdff1215c05
Revises: bfebcb56063f
Create Date: 2026-09-28 19:33:08.894393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bdff1215c05'
down_revision: Union[str, Sequence[str], None] = 'bfebcb56063f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('platform_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), server_default='backlog', nullable=False),
    sa.Column('hours_played', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('finished_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('playing', 'finished', 'dropped', 'backlog')", name='valid_status'),
    sa.CheckConstraint('finished_at >= started_at', name='finished_after_started'),
    sa.CheckConstraint('hours_played >= 0', name='non_negative_hours'),
    sa.CheckConstraint('rating BETWEEN 1 AND 10', name='rating_range'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='one_entry_per_user_game')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library_entries')
    # ### end Alembic commands ###
