"""create game_companies table

Revision ID: bfebcb56063f
Revises: 7bdadf006e31
Create Date: 2026-09-27 21:28:46.581316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfebcb56063f'
down_revision: Union[str, Sequence[str], None] = '7bdadf006e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_companies',
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('is_developer', sa.Boolean(), nullable=False),
    sa.Column('is_publisher', sa.Boolean(), nullable=False),
    sa.CheckConstraint('is_developer OR is_publisher', name='has_role'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_companies')
    # ### end Alembic commands ###
